name: OneWayElytra
version: '1.2.0-beta1'
main: de.jugglegaming.oneWayElytra.OneWayElytra
author: JuggleGaming
api-version: '26.1.2'

commands:
  onewayelytra:
    description: "OneWayElytra"
    aliases: [owe]
